services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=pg

volumes:
  pg: